name: Sync to Hugging Face Space (skip binaries)

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      # Remove all image binaries before pushing
      - name: Remove image binaries
        run: |
          find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec git rm -f --cached {} \; || echo "No binaries found"
          git commit -m "Remove binaries for HF push" || echo "No binaries to remove"

      # Push cleaned repo to Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf-space https://satyaprakashmohanty13:$HF_TOKEN@huggingface.co/spaces/satyaprakashmohanty13/Repo-push
          git push --force hf-space master:main
